# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-13 10:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllLabels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_raw', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='AllPhrases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase_raw', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AllTerms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_raw', models.CharField(max_length=100)),
                ('start_time', models.IntegerField()),
                ('createdat', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AllWeb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_raw', models.CharField(max_length=200)),
                ('web_score', models.CharField(max_length=200)),
                ('web_identity', models.CharField(max_length=200)),
                ('web_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=250)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foldername', models.CharField(max_length=200)),
                ('notes', models.CharField(max_length=2000)),
                ('main_file', models.CharField(default='', max_length=300)),
                ('reatedat', models.DateTimeField(auto_now_add=True)),
                ('createdat_string', models.CharField(default='', max_length=300)),
                ('type_complex', models.CharField(default='', max_length=300)),
                ('type_simple', models.CharField(default='', max_length=300)),
                ('format_simple', models.CharField(default='', max_length=300)),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.Context')),
            ],
        ),
        migrations.CreateModel(
            name='LabelSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_raw', models.CharField(max_length=200)),
                ('google_entity_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LongFormSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_form_string', models.CharField(max_length=500)),
                ('referencing_frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.Frame')),
            ],
        ),
        migrations.CreateModel(
            name='Mind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('email', models.CharField(default='', max_length=250)),
                ('password', models.CharField(max_length=250)),
                ('profile_picture', models.CharField(max_length=250)),
                ('datejoined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhraseSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase_raw', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TermSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_raw', models.CharField(max_length=100)),
                ('google_entity_id', models.CharField(max_length=50)),
                ('rough_count', models.IntegerField()),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('user_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.Mind')),
            ],
        ),
        migrations.CreateModel(
            name='WebSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_raw', models.CharField(max_length=200)),
                ('web_identity', models.CharField(max_length=200)),
                ('web_url', models.CharField(max_length=200)),
                ('google_entity_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='frame',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.Mind'),
        ),
        migrations.AddField(
            model_name='allweb',
            name='referencing_frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.Frame'),
        ),
        migrations.AddField(
            model_name='allweb',
            name='web_set_parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.PhraseSet'),
        ),
        migrations.AddField(
            model_name='allterms',
            name='referencing_frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.Frame'),
        ),
        migrations.AddField(
            model_name='allterms',
            name='term_set_parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.TermSet'),
        ),
        migrations.AddField(
            model_name='allterms',
            name='user_parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.Mind'),
        ),
        migrations.AddField(
            model_name='allphrases',
            name='phrase_set_parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.PhraseSet'),
        ),
        migrations.AddField(
            model_name='allphrases',
            name='referencing_frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.Frame'),
        ),
        migrations.AddField(
            model_name='alllabels',
            name='label_set_parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.LabelSet'),
        ),
        migrations.AddField(
            model_name='alllabels',
            name='referencing_frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.Frame'),
        ),
    ]
