# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 06:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllLabels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_raw', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='AllPhrases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase_raw', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AllTerms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_raw', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AllWeb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_raw', models.CharField(max_length=200)),
                ('web_score', models.CharField(max_length=200)),
                ('web_identity', models.CharField(max_length=200)),
                ('web_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LabelSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_raw', models.CharField(max_length=200)),
                ('google_entity_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PhraseSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase_raw', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TermSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_raw', models.CharField(max_length=100)),
                ('google_entity_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WebSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_raw', models.CharField(max_length=200)),
                ('web_identity', models.CharField(max_length=200)),
                ('web_url', models.CharField(max_length=200)),
                ('google_entity_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='frame',
            name='main_file',
            field=models.CharField(default='NO_FILE', max_length=300),
        ),
        migrations.AddField(
            model_name='allweb',
            name='referencing_frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.Frame'),
        ),
        migrations.AddField(
            model_name='allweb',
            name='web_set_parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.PhraseSet'),
        ),
        migrations.AddField(
            model_name='allterms',
            name='referencing_frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.Frame'),
        ),
        migrations.AddField(
            model_name='allterms',
            name='term_set_parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.TermSet'),
        ),
        migrations.AddField(
            model_name='allphrases',
            name='phrase_set_parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.PhraseSet'),
        ),
        migrations.AddField(
            model_name='allphrases',
            name='referencing_frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.Frame'),
        ),
        migrations.AddField(
            model_name='alllabels',
            name='label_set_parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.LabelSet'),
        ),
        migrations.AddField(
            model_name='alllabels',
            name='referencing_frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.Frame'),
        ),
    ]
