# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-13 10:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frame',
            old_name='reatedat',
            new_name='createdat',
        ),
    ]
