# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-13 20:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0002_auto_20180113_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='context',
            name='mind',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ingestion.Mind'),
            preserve_default=False,
        ),
    ]
