# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 08:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0002_auto_20171109_0620'),
    ]

    operations = [
        migrations.CreateModel(
            name='LongFormSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_form_string', models.CharField(max_length=500)),
                ('referencing_frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.Frame')),
            ],
        ),
    ]
