# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-04 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0004_auto_20171119_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frame',
            name='foldername',
            field=models.CharField(max_length=200),
        ),
    ]
